#!/usr/bin/env python3
"""
Export model architecture parameters as compile-time constants.

Generates config_spec.h with template-specialized constants that allow
the compiler to:
  1. Unroll loops at compile time
  2. Eliminate dead code paths (MoE vs dense)
  3. Register-allocate loop bounds
  4. Fuse operations via template metaprogramming

Usage:
    python export_compile_config.py --checkpoint checkpoints/<run>/model_best.pt \\
                                    --output esp32_m5stack/src/config_spec.h
"""

import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import torch
from model import NanoLLM


def generate_config_spec(config, output_path):
    """Generate config_spec.h with compile-time model constants."""
    
    # Compute derived values
    d_model = config['d_model']
    n_heads = config['n_heads']
    n_kv_heads = int(config.get('n_kv_heads') or n_heads)
    d_k = d_model // n_heads
    d_ff = config['d_ff']
    n_layers = config['n_layers']
    max_seq = config['max_seq_len']
    vocab_size = config['vocab_size']
    use_moe = config.get('use_moe', False)
    moe_n_experts = config.get('moe_n_experts', 0)
    moe_top_k = config.get('moe_top_k', 1)
    moe_expert_d_ff = config.get('moe_expert_d_ff', d_ff)
    moe_shared_d_ff = config.get('moe_shared_d_ff', 0)
    
    kv_dim = n_kv_heads * d_k
    head_dim = d_k
    kv_repeats = n_heads // n_kv_heads
    
    # Pre-computed inverse sqrt for common head dimensions
    inv_sqrt_dk = 1.0 / (d_k ** 0.5)
    
    header = f"""/**
 * @file config_spec.h
 * @brief Compile-time model architecture constants.
 *
 * Generated by export_compile_config.py — do not edit manually.
 *
 * These constexpr values enable the compiler to:
 *   - Unroll loops at compile time
 *   - Eliminate dead code paths (MoE vs dense, MQA vs GQA)
 *   - Register-allocate loop bounds
 *   - Fuse operations via template metaprogramming
 *
 * To switch models, regenerate this file and rebuild.
 */

#ifndef NANOLLM_CONFIG_SPEC_H
#define NANOLLM_CONFIG_SPEC_H

// ────────────────────────────────────────────────────────────────
// Architecture constants (folded into instruction addresses by linker)
// ────────────────────────────────────────────────────────────────

namespace nanollm {{

inline constexpr int CFG_D_MODEL     = {d_model};
inline constexpr int CFG_N_HEADS     = {n_heads};
inline constexpr int CFG_N_KV_HEADS  = {n_kv_heads};
inline constexpr int CFG_D_K         = {d_k};
inline constexpr int CFG_D_FF        = {d_ff};
inline constexpr int CFG_N_LAYERS    = {n_layers};
inline constexpr int CFG_MAX_SEQ_LEN = {max_seq};
inline constexpr int CFG_VOCAB_SIZE  = {vocab_size};

// MoE configuration
inline constexpr bool CFG_USE_MOE         = {"true" if use_moe else "false"};
inline constexpr int  CFG_MOE_N_EXPERTS   = {moe_n_experts};
inline constexpr int  CFG_MOE_TOP_K       = {moe_top_k};
inline constexpr int  CFG_MOE_EXPERT_D_FF = {moe_expert_d_ff};
inline constexpr int  CFG_MOE_SHARED_D_FF = {moe_shared_d_ff};

// ────────────────────────────────────────────────────────────────
// Derived constants (pre-computed for compile-time folding)
// ────────────────────────────────────────────────────────────────

inline constexpr int CFG_KV_DIM          = {kv_dim};
inline constexpr int CFG_HEAD_DIM        = {head_dim};
inline constexpr int CFG_KV_REPEATS      = {kv_repeats};
inline constexpr float CFG_INV_SQRT_DK   = {inv_sqrt_dk:.10f}f;

// Quantized memory layout (for embedding-based builds)
inline constexpr size_t CFG_QUANTIZED_WEIGHT_OVERHEAD = 1; // 1 byte per weight + 4 bytes scale
inline constexpr bool CFG_QUANTIZED = true;

// ────────────────────────────────────────────────────────────────
// Pre-computed weight dimensions (for static array sizing)
// ────────────────────────────────────────────────────────────────

// Attention weights per layer
inline constexpr size_t CFG_ATTN_Q_WEIGHTS = {d_model} * {d_model};   // Q: d_model x d_model
inline constexpr size_t CFG_ATTN_K_WEIGHTS = {d_model} * {kv_dim};    // K: d_model x kv_dim
inline constexpr size_t CFG_ATTN_V_WEIGHTS = {d_model} * {kv_dim};    // V: d_model x kv_dim
inline constexpr size_t CFG_ATTN_O_WEIGHTS = {d_model} * {d_model};   // O: d_model x d_model

// FFN weights per layer
inline constexpr size_t CFG_FF1_WEIGHTS = {d_model} * {d_ff};
inline constexpr size_t CFG_FF2_WEIGHTS = {d_ff} * {d_model};

// MoE router weights
inline constexpr size_t CFG_MOE_ROUTER_WEIGHTS = {d_model} * {moe_n_experts};

// ────────────────────────────────────────────────────────────────
// Memory budget estimates (for embedded builds)
// ────────────────────────────────────────────────────────────────

// Total quantized weight bytes per layer (dense case)
inline constexpr size_t CFG_WEIGHTS_PER_LAYER_DENSE = \\
    CFG_ATTN_Q_WEIGHTS + CFG_ATTN_K_WEIGHTS + CFG_ATTN_V_WEIGHTS + CFG_ATTN_O_WEIGHTS + \\
    CFG_FF1_WEIGHTS + CFG_FF2_WEIGHTS + \\
    2 * {d_model} + 2 * {d_model}; // 2x LayerNorm (weight + bias)

// Total quantized weight bytes for entire model
inline constexpr size_t CFG_TOTAL_WEIGHT_BYTES = \\
    {d_model} * {vocab_size} * 2 + \\  // token_emb + pos_emb (shared)
    CFG_N_LAYERS * CFG_WEIGHTS_PER_LAYER_DENSE + \\
    {d_model} + {d_model}; // final norm

// Embedding-based KV cache size
inline constexpr size_t CFG_KV_CACHE_BYTES = \\
    static_cast<size_t>(CFG_N_LAYERS) * CFG_MAX_SEQ_LEN * CFG_KV_DIM;

// Working SRAM estimate (float buffers)
inline constexpr size_t CFG_WORKING_SRAM_BYTES = \\
    static_cast<size_t>(CFG_MAX_SEQ_LEN) * CFG_D_MODEL * 5 * sizeof(float); // ~5 seq buffers

}}  // namespace nanollm

// ────────────────────────────────────────────────────────────────
// Build-time validation (compile-time assertions)
// ────────────────────────────────────────────────────────────────

// These static_asserts catch configuration errors at compile time
namespace nanollm {{

static_assert(D_MODEL % N_HEADS == 0, "d_model must be divisible by n_heads");
static_assert(N_HEADS % N_KV_HEADS == 0, "n_heads must be divisible by n_kv_heads");
static_assert(N_HEADS > 0 && N_KV_HEADS > 0, "head counts must be positive");
static_assert(D_MODEL > 0 && D_FF > 0, "model dimensions must be positive");
static_assert(MAX_SEQ_LEN > 0 && MAX_SEQ_LEN <= 1024, "sequence length out of range");
static_assert(VOCAB_SIZE > 0 && VOCAB_SIZE <= 65536, "vocab size out of range");

}}  // namespace nanollm

#endif  // NANOLLM_CONFIG_SPEC_H
"""
    
    # Fix: use CFG_ prefix for static_asserts
    header = header.replace(
        "static_assert(D_MODEL % N_HEADS",
        "static_assert(CFG_D_MODEL % CFG_N_HEADS"
    ).replace(
        "N_HEADS == 0",
        "CFG_N_HEADS == 0"
    ).replace(
        "N_KV_HEADS == 0",
        "CFG_N_KV_HEADS == 0"
    ).replace(
        "N_HEADS % N_KV_HEADS",
        "CFG_N_HEADS % CFG_N_KV_HEADS"
    ).replace(
        "D_MODEL > 0 && D_FF > 0",
        "CFG_D_MODEL > 0 && CFG_D_FF > 0"
    ).replace(
        "MAX_SEQ_LEN",
        "CFG_MAX_SEQ_LEN"
    ).replace(
        "VOCAB_SIZE",
        "CFG_VOCAB_SIZE"
    ).replace(
        "N_LAYERS",
        "CFG_N_LAYERS"
    )
    
    # Write output
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    with open(output_path, 'w') as f:
        f.write(header)
    
    return config


def main():
    parser = argparse.ArgumentParser(
        description="Export model config as compile-time constants")
    parser.add_argument("--checkpoint", required=True,
                        help="Path to PyTorch checkpoint (.pt)")
    parser.add_argument("--output", required=True,
                        help="Output header file path")
    parser.add_argument("--json-only", action="store_true",
                        help="Only output JSON, don't generate header")
    args = parser.parse_args()
    
    print(f"Loading checkpoint: {args.checkpoint}")
    checkpoint = torch.load(args.checkpoint, map_location='cpu')
    
    config = checkpoint.get('config', {})
    config['n_kv_heads'] = int(config.get('n_kv_heads') or config['n_heads'])
    
    # Add defaults
    config.setdefault('d_ff', 128)
    config.setdefault('max_seq_len', 256)
    config.setdefault('vocab_size', 50257)
    config.setdefault('use_moe', False)
    config.setdefault('moe_n_experts', 0)
    config.setdefault('moe_top_k', 1)
    config.setdefault('moe_expert_d_ff', config.get('d_ff', 128))
    config.setdefault('moe_shared_d_ff', 0)
    
    print(f"Model config: {json.dumps({k: v for k, v in config.items() if not k.startswith('_')}, indent=2)}")
    
    if args.json_only:
        print(json.dumps(config, indent=2))
        return
    
    config = generate_config_spec(config, args.output)
    print(f"Generated: {args.output}")
    
    # Print derived stats
    d_model = config['d_model']
    n_heads = config['n_heads']
    print(f"\nDerived architecture:")
    print(f"  d_model:     {d_model}")
    print(f"  n_heads:     {n_heads}")
    print(f"  n_kv_heads:  {config['n_kv_heads']}")
    print(f"  d_k (head):  {d_model // n_heads}")
    print(f"  d_ff:        {config['d_ff']}")
    print(f"  n_layers:    {config['n_layers']}")
    print(f"  use_moe:     {config.get('use_moe', False)}")


if __name__ == "__main__":
    main()
